# Implementing Multivariate Linear Regression

In [102]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [103]:
path = os.getcwd() + '\data\ex1data2.txt'

In [104]:
path

'C:\\J\\Work\\CT\\BluemineRedesign\\dev\\machinelearning\\andrew-ml-course\\git\\machine-learning-1\\linear regression\\python\\notebooks\\data\\ex1data2.txt'

In [105]:
print(path)

C:\J\Work\CT\BluemineRedesign\dev\machinelearning\andrew-ml-course\git\machine-learning-1\linear regression\python\notebooks\data\ex1data2.txt


In [143]:
data2 = pd.read_csv(path, header=None, names=['Size', 'Bedrooms', 'Price'])

In [144]:
data2.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

In [136]:
data2.describe()

Size   Bedrooms          Price
count    47.000000  47.000000      47.000000
mean   2000.680851   3.170213  340412.659574
std     794.702354   0.760982  125039.899586
min     852.000000   1.000000  169900.000000
25%    1432.000000   3.000000  249900.000000
50%    1888.000000   3.000000  299900.000000
75%    2269.000000   4.000000  384450.000000
max    4478.000000   5.000000  699900.000000

In [137]:
data2 = (data2 - data2.mean())/data2.std()

In [138]:
data2.head()

Size  Bedrooms     Price
0  0.130010 -0.223675  0.475747
1 -0.504190 -0.223675 -0.084074
2  0.502476 -0.223675  0.228626
3 -0.735723 -1.537767 -0.867025
4  1.257476  1.090417  1.595389

In [139]:
def computeCost(X, y, theta):
    inner = np.power(((X * theta.T) - y),2)
    return np.sum(inner) / (2*len(X))

In [140]:
def gradientDescent(X, y, theta, alpha, iters):
    temp = np.matrix(np.zeros(theta.shape))
    parameters = int(theta.ravel().shape[1])
    cost = np.zeros(iters)
    
    for i in range(iters):
        error = (X * theta.T) - y
        
        for j in range(parameters):
            term = np.multiply(error, X[:,j])
            temp[0,j] = theta[0,j] - ((alpha / len(X)) * np.sum(term))
            
        theta = temp
        cost[i] = computeCost(X, y, theta)
        
    return theta, cost

In [141]:
# add ones column
data2.insert(0, 'Ones', 1)

In [142]:
data2.head()

Ones      Size  Bedrooms     Price
0     1  0.130010 -0.223675  0.475747
1     1 -0.504190 -0.223675 -0.084074
2     1  0.502476 -0.223675  0.228626
3     1 -0.735723 -1.537767 -0.867025
4     1  1.257476  1.090417  1.595389

In [115]:
# set X (training data) and y (target variable)
cols = data2.shape[1]
X2 = data2.iloc[:,0:cols-1]
y2 = data2.iloc[:,cols-1:cols]

In [116]:
# convert to matrices and initialize theta
X2 = np.matrix(X2.values)
y2 = np.matrix(y2.values)
theta2 = np.matrix(np.array([0,0,0]))

In [117]:
alpha = 0.0003
iters = 100000
g2, cost2 = gradientDescent(X2, y2, theta2, alpha, iters)

In [118]:
computeCost(X2, y2, g2)

0.13068648053960882

In [119]:
g2

matrix([[-1.11021476e-16,  8.84764841e-01, -5.31776724e-02]])

## Using sklearn

In [123]:
cols = data2.shape[1]
X = data2.iloc[:,0:cols-1]
y = data2.iloc[:,cols-1:cols]

In [125]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [128]:
predictions = model.predict(X)

In [131]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y,predictions)
rmse = np.sqrt(mse)
rmse

0.5112464778148441

In [145]:
data2 = pd.read_csv(path, header=None, names=['Size', 'Bedrooms', 'Price'])

In [146]:
data2.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

In [147]:
# add ones column
data2.insert(0, 'Ones', 1)

In [148]:
data2.head()

Ones  Size  Bedrooms   Price
0     1  2104         3  399900
1     1  1600         3  329900
2     1  2400         3  369000
3     1  1416         2  232000
4     1  3000         4  539900

In [149]:
cols = data2.shape[1]
X = data2.iloc[:,0:cols-1]
y = data2.iloc[:,cols-1:cols]

In [155]:
X.head()

Ones  Size  Bedrooms
0     1  2104         3
1     1  1600         3
2     1  2400         3
3     1  1416         2
4     1  3000         4

In [156]:
X = np.matrix(X.values)

In [157]:
A = X.T * X

In [159]:
X.shape

(47, 3)

In [163]:
X[:5]

matrix([[   1, 2104,    3],
        [   1, 1600,    3],
        [   1, 2400,    3],
        [   1, 1416,    2],
        [   1, 3000,    4]], dtype=int64)

In [161]:
B = np.linalg.inv(A)

In [162]:
B.shape

(3, 3)

In [164]:
B[:5]

matrix([[ 3.99642990e-01, -7.36150728e-06, -1.14704720e-01],
        [-7.36150728e-06,  5.01455797e-08, -2.93241497e-05],
        [-1.14704720e-01, -2.93241497e-05,  5.46881227e-02]])

In [165]:
C = B * X.T

In [166]:
C.shape

(3, 47)

In [168]:
C[:1]

matrix([[ 0.04004022,  0.04375042,  0.03786121,  0.15980966, -0.08126041,
         -0.07378848,  0.04423628,  0.04502396,  0.04536995,  0.04453074,
         -0.07345721,  0.04080582,  0.04161558, -0.20684544,  0.04619444,
         -0.07610736,  0.16051636,  0.04643001, -0.07838206, -0.08148862,
          0.04252105,  0.15633502,  0.04372097, -0.07361917,  0.02689257,
          0.04743117,  0.04479575,  0.03693366,  0.03933351,  0.03611654,
          0.15669574,  0.27757676, -0.07419336,  0.03243578, -0.07250758,
          0.04495034,  0.04640792, -0.07487062, -0.09020464, -0.07509147,
          0.157984  ,  0.03905378, -0.07807288,  0.04669502,  0.16396155,
         -0.0728094 ,  0.04667294]])

In [169]:
y = np.matrix(y.values)

In [170]:
T = C * y

In [171]:
T

matrix([[89597.9095428 ],
        [  139.21067402],
        [-8738.01911233]])